import dedent from 'dedent'
import fse from 'fs-extra'
import pathe from 'pathe'

export function generateDeclarations(modules: string[]) {
  const dts = modules.map((item) => {
    return dedent`
      declare module '${item}' {
        const SvgSpriteSymbol: (props: React.SVGProps<SVGSVGElement>) => React.ReactNode
        export default SvgSpriteSymbol
      }
    `.trim()
  })

  const prefix = dedent`
    /* eslint-disable */
    /* prettier-ignore */
    // @ts-nocheck
    // noinspection JSUnusedGlobalSymbols
    // Generated by unplugin-svg-sprite
  `

  const result = `${prefix}\n\n${dts.join('\n\n')}`

  fse.writeFileSync(
    pathe.join(process.cwd(), 'svg-sprite.d.ts'),
    result,
    'utf-8',
  )
}
