import dedent from 'dedent'
import fse from 'fs-extra'
import pathe from 'pathe'

export async function generateDeclarations(
  modules: string[],
  normalize?: (module: string) => string,
) {
  const mergedNormalize =
    normalize ||
    ((module) => {
      return `
        declare module '${module}' {
          const SvgSpriteSymbol: (props: any) => any
          export default SvgSpriteSymbol
        }
      `
    })

  const dts = modules.map((item) => {
    return dedent`
      ${mergedNormalize(item)}
    `.trim()
  })

  const prefix = dedent`
    /* eslint-disable */
    /* prettier-ignore */
    // @ts-nocheck
    // noinspection JSUnusedGlobalSymbols
    // Generated by unplugin-svg-sprite
  `

  const result = `${prefix}\n\n${dts.join('\n\n')}`

  await fse.writeFile(
    pathe.join(process.cwd(), 'svg-sprite.d.ts'),
    result,
    'utf-8',
  )
}
