/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-svg-sprite

declare module '~svg-sprite/symbol/assets/vercel' {
  const SvgSpriteSymbol: (props: React.SVGProps<SVGSVGElement>) => React.ReactNode
  export default SvgSpriteSymbol
}

declare module '~svg-sprite/symbol/assets/raw/react' {
  const SvgSpriteSymbol: (
    props: React.SVGProps<SVGSVGElement>,
  ) => React.ReactNode
  export default SvgSpriteSymbol
}

declare module '~svg-sprite/symbol/assets/raw/vercel' {
  const SvgSpriteSymbol: (
    props: React.SVGProps<SVGSVGElement>,
  ) => React.ReactNode
  export default SvgSpriteSymbol
}

declare module '~svg-sprite/symbol/assets/raw/vite' {
  const SvgSpriteSymbol: (
    props: React.SVGProps<SVGSVGElement>,
  ) => React.ReactNode
  export default SvgSpriteSymbol
}
